/**
 * Downloads the ambientCG materials listed in texture-spec.ts into assets/raw/<id>/ and
 * writes assets/CREDITS.md. Idempotent: assets already on disk are skipped.
 *
 *   npm run textures:fetch
 *
 * Only ambientCG is used: every asset there is CC0 1.0 Universal
 * (https://docs.ambientcg.com/license/). The script refuses anything that is not a
 * ambientCG "Material" returned by the official API.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { unzipSync } from 'fflate';
import { ambientCgIds, TEXTURE_SPEC, type VariantSource } from './texture-spec.ts';

const ROOT = new URL('..', import.meta.url).pathname;
const RAW_DIR = join(ROOT, 'assets/raw');
const API = 'https://ambientcg.com/api/v2/full_json';
const RESOLUTION = '1K-JPG';
const CONCURRENCY = 4;
/** Maps kept from each archive (suffix after `<id>_1K-JPG_`). */
const MAPS = ['Color', 'NormalGL', 'Roughness', 'AmbientOcclusion', 'Displacement', 'Opacity', 'Metalness', 'Emission'];

interface ApiAsset {
  assetId: string;
  displayName: string;
  dataType: string;
  downloadFolders?: Record<
    string,
    { downloadFiletypeCategories?: Record<string, { downloads?: { attribute: string; downloadLink: string; size: number }[] }> }
  >;
}

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return (await res.json()) as T;
}

async function queryAssets(ids: string[]): Promise<Map<string, ApiAsset>> {
  const url = `${API}?id=${ids.join(',')}&include=downloadData&limit=${ids.length}`;
  const data = await fetchJson<{ foundAssets: ApiAsset[] }>(url);
  return new Map(data.foundAssets.map((a) => [a.assetId, a]));
}

function downloadLink(asset: ApiAsset): string {
  for (const folder of Object.values(asset.downloadFolders ?? {})) {
    for (const cat of Object.values(folder.downloadFiletypeCategories ?? {})) {
      const hit = cat.downloads?.find((d) => d.attribute === RESOLUTION);
      if (hit) return hit.downloadLink;
    }
  }
  throw new Error(`${asset.assetId}: no ${RESOLUTION} download`);
}

async function download(asset: ApiAsset): Promise<string> {
  const dir = join(RAW_DIR, asset.assetId);
  if (existsSync(join(dir, 'Color.jpg'))) return 'cached';
  const url = downloadLink(asset);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${asset.assetId}: ${res.status} ${res.statusText}`);
  const zip = unzipSync(new Uint8Array(await res.arrayBuffer()));
  mkdirSync(dir, { recursive: true });
  let kept = 0;
  for (const [name, bytes] of Object.entries(zip)) {
    const map = MAPS.find((m) => name.endsWith(`_${m}.jpg`));
    if (!map) continue;
    writeFileSync(join(dir, `${map}.jpg`), bytes);
    kept++;
  }
  if (!existsSync(join(dir, 'Color.jpg'))) throw new Error(`${asset.assetId}: archive has no Color map`);
  return `${kept} maps`;
}

function describe(v: VariantSource): string {
  switch (v.kind) {
    case 'ambientcg':
      return `[${v.id}](https://ambientcg.com/a/${v.id})${v.crop < 1 ? `, cropped to ${Math.round(v.crop * 100)} % and re-tiled` : ''}`;
    case 'grass-side':
      return `composite of [${v.dirt}](https://ambientcg.com/a/${v.dirt}) + [${v.grass}](https://ambientcg.com/a/${v.grass})`;
    case 'leaves':
      return `scattered from ${v.sprites.map((s) => `[${s}](https://ambientcg.com/a/${s})`).join(' + ')}`;
    case 'procedural':
      return `procedural (\`${v.generator}\`, generated by build-textures.ts)`;
  }
}

function writeCredits(assets: Map<string, ApiAsset>): void {
  const lines = [
    '# Texture credits',
    '',
    'Generated by `npm run textures:fetch` — do not edit by hand.',
    '',
    'All downloaded textures come from [ambientCG](https://ambientcg.com) and are licensed',
    'under **Creative Commons CC0 1.0 Universal** ([license](https://docs.ambientcg.com/license/)).',
    'No attribution is required; it is listed here for transparency.',
    '',
    '## Per material',
    '',
    '| Material | Variant | Source |',
    '| --- | --- | --- |',
  ];
  for (const [material, spec] of Object.entries(TEXTURE_SPEC)) {
    spec.variants.forEach((v, i) => lines.push(`| ${material} | ${i + 1} | ${describe(v)} |`));
  }
  lines.push('', '## Assets', '', '| Asset | Name | License |', '| --- | --- | --- |');
  for (const id of ambientCgIds()) {
    const a = assets.get(id);
    lines.push(`| [${id}](https://ambientcg.com/a/${id}) | ${a?.displayName ?? id} | CC0 1.0 |`);
  }
  writeFileSync(join(ROOT, 'assets/CREDITS.md'), `${lines.join('\n')}\n`);
}

async function main(): Promise<void> {
  const ids = ambientCgIds();
  console.log(`ambientCG assets: ${ids.length}`);
  const assets = await queryAssets(ids);
  const missing = ids.filter((id) => !assets.has(id));
  if (missing.length) throw new Error(`not found on ambientCG: ${missing.join(', ')}`);
  for (const a of assets.values()) {
    if (a.dataType !== 'Material') throw new Error(`${a.assetId} is a ${a.dataType}, expected Material`);
  }

  const queue = [...assets.values()];
  let failed = 0;
  await Promise.all(
    Array.from({ length: CONCURRENCY }, async () => {
      for (let a = queue.shift(); a; a = queue.shift()) {
        try {
          console.log(`  ${a.assetId}: ${await download(a)}`);
        } catch (err) {
          failed++;
          console.error(`  ${a.assetId}: FAILED — ${err instanceof Error ? err.message : err}`);
        }
      }
    }),
  );
  writeCredits(assets);
  console.log('wrote assets/CREDITS.md');
  if (failed) {
    console.error(`${failed} download(s) failed; run again to retry.`);
    process.exit(1);
  }
}

await main();
